# Render deployment configuration
# Updated to fix Rollup module issue
services:
  - type: web
    name: codeswitch
    env: node
    plan: starter
    buildCommand: rm -rf node_modules package-lock.json && npm cache clean --force && npm install && npm install @tailwindcss/typography tailwindcss-animate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: XAI_API_KEY
        sync: false
      - key: FREE_TIER_ENABLED
        value: true
      - key: FREE_TIER_DAILY_LIMIT
        value: 5
      - key: RATE_LIMIT_WINDOW_SECONDS
        value: 60
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 30
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_PRICE_BASIC
        sync: false
      - key: STRIPE_PRICE_PRO
        sync: false
      - key: NODE_VERSION
        value: 18.x
    build:
      nodeVersion: 18
    healthCheckPath: /api/health
    autoDeploy: true
